server:
  port: 9191

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: BOOK-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/books/**
        - id: AUTHOR-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**
        - id: LOGIN
          uri: http://localhost:8082
          predicates:
            - Path=/login/**
