server:
  port: 9191

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: BOOK-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/books/**
        - id: AUTHOR-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**
